# Generated by Django 3.2.12 on 2022-06-07 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('skills', models.CharField(max_length=300, null=True)),
                ('applicant_dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('year_experience', models.IntegerField(blank=True, null=True)),
                ('month_experience', models.IntegerField(blank=True, null=True)),
                ('previous_work', models.TextField(blank=True, max_length=3000, null=True)),
                ('intro', models.FileField(blank=True, null=True, upload_to='')),
                ('aadhar_card', models.FileField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('pancard', models.FileField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('disability_certificate', models.FileField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('certifications', models.FileField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_logo', models.ImageField(blank=True, default='profile2.png', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Jobcreate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_position', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=300, null=True)),
                ('disability', models.CharField(max_length=100, null=True)),
                ('job_description', models.TextField(max_length=3000, null=True)),
                ('min_salary', models.IntegerField(null=True)),
                ('max_salary', models.IntegerField(null=True)),
                ('min_experience', models.IntegerField(null=True)),
                ('max_experience', models.IntegerField(null=True)),
                ('Location', models.CharField(max_length=2000, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 7, 21, 9, 57, 283395))),
                ('job_category', models.CharField(choices=[('Accounting and Consulting', 'Accounting and Consulting'), ('Admin Support', 'Admin Support'), ('Customer Service', 'Customer Service'), ('Data Science and Analysis', 'Data Science and Analysis'), ('Design and Creative', 'Design and Creative'), ('Engineering and Architecture', 'Engineering and Architecture'), ('IT and Networking', 'IT and Networking'), ('Legal', 'Legal'), ('Sales and Marketing', 'Sales and Marketing'), ('Translation', 'Translation'), ('Web, Mobile, and Software Development', 'Web, Mobile, and Software Development'), ('Writing', 'Writing'), ('Others', 'Others')], default='Others', max_length=200)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=200, null=True)),
                ('invite_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 7, 21, 9, 57, 283395))),
                ('applicant_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.candidates')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.company')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.jobcreate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=200, null=True)),
                ('application_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 7, 21, 9, 57, 283395))),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.company')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobPortal.jobcreate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
