# Generated by Django 4.0.6 on 2022-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_project_short_description_alter_project_srno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('filter', models.CharField(choices=[('programming', 'programming'), ('cloud', 'cloud'), ('networking', 'networking'), ('other', 'other')], max_length=200)),
                ('pic', models.ImageField(blank=True, default='blank.png', null=True, upload_to='')),
            ],
        ),
    ]
