# Generated by Django 4.0.6 on 2022-08-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
